### ISSUE TITLE
"errorMessage": "Cannot find module '/var/task/index'"

### ISSUE THREAD

**Issue by rafaeldrs** [lubos/aws-lambda-wkhtmltopdf#4]
Hello, 

I followed your steps, but when I click on test the following error appears:

{
  "errorMessage": "Cannot find module '/var/task/index'",
  "errorType": "Error",
  "stackTrace": [
    "Function.Module._load (module.js:276:25)",
    "Module.require (module.js:353:17)",
    "require (internal/module.js:12:17)"
  ]
}

It seems like any module is not loading correctly but I couldn't find the issue.

Thanks for your time.

**Comment by tonydemark** [comment]
The archive you are creating for AWS is in a directory.

That is:

```directory/
directory/node_modules/
directory/README.md
directory/index.js
directory/wkhtmltopdf
```

Instead, generate the archive WITHOUT the enclosing directory:

```
node_modules/
README.md
index.js
wkhtmltopdf
```

**Comment by rafaeldrs** [comment]
Thanks so much, thats It!
