### ISSUE TITLE
Problem when unzipping and zipping again

### ISSUE THREAD

**Issue by rafaeldrs** [lubos/aws-lambda-wkhtmltopdf#5]
Hello,

When I follow your steps, the project works as intended but I need to modify the index.js to add some logic on it.

If I unzip the project and zip it again (without modifying a single line of code) it doesn't work anymore.

memStream.read() in line 9 becomes null, so when it does memStream.read().toString() it throws an error.

What can I do to add more logic to the process?

**Comment by lubos** [comment]
You need to chmod the wkthmltopdf binary to be executable.

If you don't know how to do this in new ZIP file, then just edit `index.js` within the existing zip file without touching wkhtmltopdf binary.

**Comment by rafaeldrs** [comment]
Thank you, that worked!
