### ISSUE TITLE
Mobile Browsers Issue

### ISSUE THREAD

**Issue by bculpepper** [lubos/aws-lambda-wkhtmltopdf#7]
This works fine for me on a desktop browser but on a mobile browser the file is downloaded but not recognized as a .pdf. When I open the downloaded file in chrome it just has the request body contents as such:

%PDF-1.4
1 0 obj
<<
/Title (��)
/Creator (��wkhtmltopdf 0.12.3-dev-79ff51e)
/Producer (��Qt 4.8.7)
/CreationDate (D:20170505202615Z)
>>
endobj
...

And so-on. I am completely stumped. Any ideas what could be causing this behavior on mobile browsers?

Thanks for the help!

Brandon Culpepper

**Comment by lubos** [comment]
You have an issue elsewhere. Maybe HTTP headers, maybe mobile browser not recognizing content type. Whatever it is, it has nothing to do with this project. This project merely generates PDF. How it's served to clients (desktop or mobile) is outside of the scope.
